/**
 * Copies ABIs from contracts/out/*.sol/*.json into web/lib/contracts.ts.
 * Run after every forge build that changes contract surfaces.
 */

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join, resolve } from "node:path";

const ROOT = resolve(__dirname, "..");
const OUT = join(ROOT, "contracts", "out");
const TARGET = join(ROOT, "web", "lib", "contracts.ts");

const artifacts = {
  payrollAbi: join(OUT, "Payroll.sol", "Payroll.json"),
  payrollFactoryAbi: join(OUT, "PayrollFactory.sol", "PayrollFactory.json"),
  cUSDCAbi: join(OUT, "cUSDC.sol", "cUSDC.json"),
  usdcAbi: join(OUT, "MockUSDC.sol", "MockUSDC.json"),
};

function loadAbi(path: string): unknown[] {
  if (!existsSync(path)) {
    console.warn(`[gen-abi] missing ${path} — run 'forge build' first`);
    return [];
  }
  const json = JSON.parse(readFileSync(path, "utf8"));
  return json.abi ?? [];
}

const abis = Object.fromEntries(
  Object.entries(artifacts).map(([k, p]) => [k, loadAbi(p)])
);

const content = `/**
 * Generated by \`pnpm gen-abi\`. Do not edit by hand.
 */

import { isAddress } from "viem";
import { env } from "./env";

export const addresses = {
  payroll: env.NEXT_PUBLIC_PAYROLL_ADDR as \`0x\${string}\`,
  factory: env.NEXT_PUBLIC_FACTORY_ADDR as \`0x\${string}\`,
  cUSDC: env.NEXT_PUBLIC_CUSDC_ADDR as \`0x\${string}\`,
  usdc: env.NEXT_PUBLIC_USDC_ADDR as \`0x\${string}\`,
} as const;

export function isDeployed(): boolean {
  return (
    isAddress(addresses.payroll) &&
    isAddress(addresses.cUSDC) &&
    isAddress(addresses.usdc)
  );
}

export function isFactoryDeployed(): boolean {
  return isAddress(addresses.factory);
}

export const payrollAbi = ${JSON.stringify(abis.payrollAbi, null, 2)} as const;
export const payrollFactoryAbi = ${JSON.stringify(abis.payrollFactoryAbi, null, 2)} as const;
export const cUSDCAbi = ${JSON.stringify(abis.cUSDCAbi, null, 2)} as const;
export const usdcAbi = ${JSON.stringify(abis.usdcAbi, null, 2)} as const;
`;

writeFileSync(TARGET, content);
console.log(`[gen-abi] wrote ${TARGET}`);
